### ISSUE TITLE
Binaries should be executable

### ISSUE THREAD

**Issue by bayandin** [operasoftware/operachromiumdriver#1]
``` bash
python2.7 desktop.py
Traceback (most recent call last):
  File "desktop.py", line 8, in <module>
    webdriver_service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/service.py", line 66, in start
    "ChromeDriver executable needs to be available in the path. "
selenium.common.exceptions.WebDriverException: Message: ChromeDriver executable needs to be available in the path. Please download from http://chromedriver.storage.googleapis.com/index.html and read up at http://code.google.com/p/selenium/wiki/ChromeDriver

```

After `chmod +x bin/mac/x86_64/operadriver` everything works.

**Comment by bayandin** [comment]
Hey,
Again not executable in [v0.2.2](https://github.com/operasoftware/operachromiumdriver/releases/tag/v0.2.2).
