### ISSUE TITLE
http.client.BadStatusLine: '' in Python

### ISSUE THREAD

**Issue by einsteinsfool** [operasoftware/operachromiumdriver#30]
I wrote the following code:
```python
from selenium import webdriver

capabilities = webdriver.DesiredCapabilities.OPERA.copy()
capabilities['platform'] = "LINUX"
capabilities['chromeOptions'] = {
    "binary" : "/usr/bin/opera"
}
browser = webdriver.Opera(desired_capabilities=capabilities)
browser.get('http://seleniumhq.org/')
browser.quit()
```

...and I got this error:
```
Traceback (most recent call last):
  File "tests/OperaTest.py", line 8, in <module>
    browser = webdriver.Opera(desired_capabilities=capabilities)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/opera/webdriver.py", line 73, in __init__
    service_log_path=service_log_path)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/opera/webdriver.py", line 52, in __init__
    service_log_path=service_log_path)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py", line 408, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py", line 440, in _request
    resp = self._conn.getresponse()
  File "/usr/lib64/python3.4/http/client.py", line 1227, in getresponse
    response.begin()
  File "/usr/lib64/python3.4/http/client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.4/http/client.py", line 356, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

Without DesiredCapabilities I get another error which I reported in #31.

**Versions**
Python 3.4.5
Operadriver 0.2.2
Python bindings 3.0.2
Opera 42.0.2393.85
CentOS 7.3.1611
Not using Selenium Server Standalone.

**Comment by HelioGuilherme66** [comment]
I see the same error on:
**Versions**
Python 2.7.10
Operadriver 0.2.2
Python bindings 2.53.6
Opera 42.0.2393.85
Fedora Core 22

```
Traceback (most recent call last):
  File "operadriver_test.py", line 8, in <module>
    broswer = webdriver.Opera(desired_capabilities=capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/opera/webdriver.py", line 73, in __init__
    service_log_path=service_log_path)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/opera/webdriver.py", line 52, in __init__
    service_log_path=service_log_path)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by wladzynski** [comment]
Hi! 
Is this issue still reproducible with the latest operadriver releases?

**Comment by einsteinsfool** [comment]
Just to confirm, tried it now with operachromiumdriver 2.33 and Opera 51 and didn't get any errors.
So the issue is fixed.
