### ISSUE TITLE
operadriver 78.0.3904.87: Permission denied: 'operadriver'

### ISSUE THREAD

**Issue by o-sys-256** [operasoftware/operachromiumdriver#76]
Code:

    def get_opera():
        return webdriver.Opera()

    driver = get_opera()

Tried also this:

    def get_opera():
        options = webdriver.ChromeOptions()
        options.binary_location = "/usr/local/bin/"
        return webdriver.Opera()

    driver = get_opera()

Got this error with both:

    Traceback (most recent call last):
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
        stdin=PIPE)
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: 'operadriver'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "bot.py", line 186, in <module>
        main()
      File "bot.py", line 182, in main
        bot = Bot()
      File "bot.py", line 171, in __init__
        driver = get_opera()
      File "bot.py", line 74, in get_opera
        return webdriver.Opera()
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/opera/webdriver.py", line 83, in __init__
        service_log_path=service_log_path)
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/opera/webdriver.py", line 62, in __init__
        keep_alive=keep_alive)
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
        self.service.start()
      File "/Users/User/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
        os.path.basename(self.path), self.start_error_message)
    selenium.common.exceptions.WebDriverException: Message: 'operadriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

__________________________________________

operadriver 78.0.3904.87
opera 65.0.3467.72 

I am using mac and the operadriver binary (alias) is in /usr/local/bin/
Maybe I have not correctly installed the operadriver and it is not in the right folder (?)

**Comment by o-sys-256** [comment]
Solved!

In /usr/local/bin/ folder the binary was an alias of the real binary. I moved the real executable there an it worked.

**Comment by joaoefornazari** [comment]
Could you help me?
I did what you say and it's still not working. Did you install the operadriver? Or just downloaded the .zip, extracted it and moved it to the bin folder?
